name = "anchen-jossie-website"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:vite"
publish = "dist"

[build.environment_variables]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {header = "Accept", value = "text/html"}
